[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts =
    -ra
    --strict-markers
    --alluredir=reports/allure-results
markers =
    integration: testes que dependem de componentes externos reais
    postgres: testes de integração PostgreSQL
    opensearch: testes de integração OpenSearch
