[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts =
    -ra
    --strict-markers
    --html=reports/test-report.html
    --self-contained-html
markers =
    integration: testes que dependem de componentes externos reais
    postgres: testes de integração PostgreSQL
    opensearch: testes de integração OpenSearch
    dashboards: testes de integração OpenSearch Dashboards
    client_data: testes integrados de dados de clientes
